export const LOADING_ISSUES = 'LOADING_ISSUES';
export const CURRENT_PAGE_LOADED = 'CURRENT_PAGE_LOADED';
export const ISSUES_ERROR = 'ISSUES_ERROR';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const PAGE_LOADED = 'PAGE_LOADED';


export const ISSUE_LOADED = 'ISSUE_LOADED';
export const ISSUE_ERROR = 'ISSUE_ERROR';
export const COMMENTS_LOADED = 'COMMENTS_LOADED';
export const COMMENTS_ERROR = 'COMMENTS_ERROR';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';
