export const LOADING_ISSUES = "LOADING_ISSUES";
export const CURRENT_PAGE_LOADED = "CURRENT_PAGE_LOADED";
export const ISSUES_ERROR = "ISSUES_ERROR";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const PAGE_LOADED = "PAGE_LOADED";
